const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7); const fmt=n=>(Number(n)||0).toLocaleString('fa-IR');
const DBKEY='rozeh-manager-v3';
const defaultOccasions=[
 {id:'fx0101',title:'نوروز',month:1,day:1,fixed:true},{id:'fx0102',title:'عید نوروز',month:1,day:2,fixed:true},{id:'fx0103',title:'عید نوروز',month:1,day:3,fixed:true},{id:'fx0104',title:'عید نوروز',month:1,day:4,fixed:true},{id:'fx0112',title:'روز جمهوری اسلامی',month:1,day:12,fixed:true},{id:'fx0113',title:'روز طبیعت',month:1,day:13,fixed:true},{id:'fx0212',title:'روز معلم',month:2,day:12,fixed:true},{id:'fx0314',title:'رحلت امام خمینی',month:3,day:14,fixed:true},{id:'fx0315',title:'قیام ۱۵ خرداد',month:3,day:15,fixed:true},{id:'fx1122',title:'پیروزی انقلاب اسلامی',month:11,day:22,fixed:true},{id:'fx1229',title:'ملی شدن صنعت نفت',month:12,day:29,fixed:true}
];
const emptyDB=()=>({sponsors:[],workers:[],rozehs:[],transactions:[],occasions:defaultOccasions.map(x=>({...x})),audit:[],settings:{org:'مدیریت روضه',currency:'ریال',pin:'',reminder:'1'},meta:{version:3,updatedAt:new Date().toISOString()}});
let db=(()=>{try{const d=JSON.parse(localStorage.getItem(DBKEY)||localStorage.getItem('rozeh-manager-v2')||'null');if(!d)return emptyDB();return {...emptyDB(),...d,settings:{...emptyDB().settings,...(d.settings||{})},occasions:d.occasions||defaultOccasions.map(x=>({...x})),audit:d.audit||[]};}catch{return emptyDB()}})();
function openLocalDB(){return new Promise((res,rej)=>{const q=indexedDB.open('rozeh-manager',2);q.onupgradeneeded=()=>{const x=q.result;if(!x.objectStoreNames.contains('state'))x.createObjectStore('state')};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function mirror(){try{const x=await openLocalDB();await new Promise((res,rej)=>{const t=x.transaction('state','readwrite');t.objectStore('state').put(db,'app-v3');t.oncomplete=res;t.onerror=()=>rej(t.error)});$('#storageStatus').textContent='ذخیره محلی فعال است و یک نسخه دوم در IndexedDB نگهداری می‌شود.'}catch{$('#storageStatus').textContent='اطلاعات در حافظه مرورگر ذخیره می‌شود.'}}
async function recover(){try{const x=await openLocalDB();const data=await new Promise((res,rej)=>{const t=x.transaction('state','readonly'),r=t.objectStore('state').get('app-v3');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(data&&Date.parse(data.meta?.updatedAt||0)>Date.parse(db.meta?.updatedAt||0)){db=data;localStorage.setItem(DBKEY,JSON.stringify(db));renderAll()}mirror()}catch{}}
function logAction(text){db.audit.unshift({id:uid(),text,at:new Date().toISOString()});db.audit=db.audit.slice(0,300)}
function save(action=''){if(action)logAction(action);db.meta={version:3,updatedAt:new Date().toISOString()};localStorage.setItem(DBKEY,JSON.stringify(db));mirror();renderAll()}
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1900)};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return `${fmt(n)} ${db.settings.currency}`}

function div(a,b){return ~~(a/b)} function mod(a,b){return a-~~(a/b)*b}
function jalCal(jy){const breaks=[-61,9,38,199,426,686,756,818,1111,1181,1210,1635,2060,2097,2192,2262,2324,2394,2456,3178];let bl=breaks.length,gy=jy+621,leapJ=-14,jp=breaks[0],jm,jump,n,i;if(jy<jp||jy>=breaks[bl-1])throw Error('Invalid Jalali year');for(i=1;i<bl;i++){jm=breaks[i];jump=jm-jp;if(jy<jm)break;leapJ+=div(jump,33)*8+div(mod(jump,33),4);jp=jm}n=jy-jp;leapJ+=div(n,33)*8+div(mod(n,33)+3,4);if(mod(jump,33)===4&&jump-n===4)leapJ++;const leapG=div(gy,4)-div((div(gy,100)+1)*3,4)-150,march=20+leapJ-leapG;if(jump-n<6)n=n-jump+div(jump+4,33)*33;let leap=mod(mod(n+1,33)-1,4);if(leap===-1)leap=4;return{leap,gy,march}}
function g2d(gy,gm,gd){let d=div((gy+div(gm-8,6)+100100)*1461,4)+div(153*mod(gm+9,12)+2,5)+gd-34840408;d=d-div(div(gy+100100+div(gm-8,6),100)*3,4)+752;return d}
function d2g(jdn){let j=4*jdn+139361631;j=j+div(div(4*jdn+183187720,146097)*3,4)*4-3908;const i=div(mod(j,1461),4)*5+308,gd=div(mod(i,153),5)+1,gm=mod(div(i,153),12)+1,gy=div(j,1461)-100100+div(8-gm,6);return{gy,gm,gd}}
function j2d(jy,jm,jd){const r=jalCal(jy);return g2d(r.gy,3,r.march)+(jm-1)*31-div(jm,7)*(jm-7)+jd-1}
function d2j(jdn){const g=d2g(jdn),jy=g.gy-621,r=jalCal(jy),jdn1f=g2d(g.gy,3,r.march);let k=jdn-jdn1f,jm,jd,jy2=jy;if(k>=0){if(k<=185){jm=1+div(k,31);jd=mod(k,31)+1;return{jy:jy2,jm,jd}}k-=186}else{jy2--;k+=179;if(r.leap===1)k++}jm=7+div(k,30);jd=mod(k,30)+1;return{jy:jy2,jm,jd}}
const toJalali=(gy,gm,gd)=>d2j(g2d(gy,gm,gd)),toGregorian=(jy,jm,jd)=>d2g(j2d(jy,jm,jd));
const jMonths=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
function jDaysInMonth(y,m){if(m<=6)return 31;if(m<=11)return 30;return jalCal(y).leap===0?30:29} function jKey(y,m,d){return `${y}/${String(m).padStart(2,'0')}/${String(d).padStart(2,'0')}`} function parseJ(s){const [y,m,d]=String(s).split('/').map(Number);return{y,m,d}} function validJ(s){try{const p=parseJ(s);return !!p.y&&p.m>=1&&p.m<=12&&p.d>=1&&p.d<=jDaysInMonth(p.y,p.m)}catch{return false}} function compareJ(a,b){if(!validJ(a)||!validJ(b))return 0;const A=parseJ(a),B=parseJ(b);return j2d(A.y,A.m,A.d)-j2d(B.y,B.m,B.d)} function todayJ(){const d=new Date(),j=toJalali(d.getFullYear(),d.getMonth()+1,d.getDate());return jKey(j.jy,j.jm,j.jd)}
function dayDiff(a,b){if(!validJ(a)||!validJ(b))return 9999;const A=parseJ(a),B=parseJ(b);return j2d(A.y,A.m,A.d)-j2d(B.y,B.m,B.d)}
let nowJ=parseJ(todayJ()),calYear=nowJ.y,calMonth=nowJ.m,accountTab='sponsors';
const sponsorBy=id=>db.sponsors.find(x=>x.id===id),workerBy=id=>db.workers.find(x=>x.id===id),rozehBy=id=>db.rozehs.find(x=>x.id===id);
const expenseTotal=r=>(r.expenses||[]).reduce((s,e)=>s+(Number(e.qty)||0)*(Number(e.amount)||0),0); const sponsorCharge=r=>Number(r.sponsorCharge)||expenseTotal(r);
function sponsorPaid(id){return db.transactions.filter(t=>t.partyType==='sponsor'&&t.partyId===id&&t.kind==='receive').reduce((s,t)=>s+Number(t.amount||0),0)} function sponsorDebt(id){return db.rozehs.filter(r=>r.sponsorId===id).reduce((s,r)=>s+sponsorCharge(r),0)-sponsorPaid(id)}
function workerDue(id){let due=0;db.rozehs.forEach(r=>(r.expenses||[]).forEach(e=>{if(e.workerId===id&&e.attended!==false)due+=(Number(e.qty)||0)*(Number(e.amount)||0)}));return due} function workerPaid(id){return db.transactions.filter(t=>t.partyType==='worker'&&t.partyId===id&&t.kind==='pay').reduce((s,t)=>s+Number(t.amount||0),0)} function workerBalance(id){return workerDue(id)-workerPaid(id)}
function occasionFor(y,m,d){const exact=jKey(y,m,d);return db.occasions.filter(o=>o.date===exact||(o.fixed&&Number(o.month)===m&&Number(o.day)===d)).map(o=>o.title).join(' • ')}
function stat(label,value){return `<div class="stat"><span>${esc(label)}</span><b>${value}</b></div>`}
function modalHead(t){return `<div class="modal-head"><h2>${esc(t)}</h2><button type="button" class="close-btn">×</button></div>`}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').showModal();$$('.close-btn').forEach(b=>b.onclick=()=>$('#modal').close())}

function renderCalendar(){
 $('#monthTitle').textContent=`${jMonths[calMonth-1]} ${fmt(calYear)}`;const g=$('#calendarGrid');g.innerHTML='';const gd=toGregorian(calYear,calMonth,1),offset=(new Date(gd.gy,gd.gm-1,gd.gd).getDay()+1)%7;for(let i=0;i<offset;i++)g.insertAdjacentHTML('beforeend','<div class="day empty"></div>');
 for(let d=1;d<=jDaysInMonth(calYear,calMonth);d++){const key=jKey(calYear,calMonth,d),r=db.rozehs.find(x=>(x.dates||[]).includes(key)),occ=occasionFor(calYear,calMonth,d),label=r?(sponsorBy(r.sponsorId)?.name||'رزرو شده'):occ,cls=`day ${r?'booked':''} ${!r&&occ?'occasion':''} ${key===todayJ()?'today':''}`;g.insertAdjacentHTML('beforeend',`<button class="${cls}" data-date="${key}"><span class="num">${fmt(d)}</span>${label?`<span class="label">${esc(label)}</span>`:''}</button>`)}
 $$('.day[data-date]').forEach(b=>b.onclick=()=>dayClicked(b.dataset.date));
}
function renderDashboard(){const pref=`${calYear}/${String(calMonth).padStart(2,'0')}`,booked=db.rozehs.reduce((s,r)=>s+(r.dates||[]).filter(d=>d.startsWith(pref)).length,0),recv=db.transactions.filter(t=>t.kind==='receive').reduce((s,t)=>s+Number(t.amount||0),0),sDebt=db.sponsors.reduce((s,x)=>s+Math.max(0,sponsorDebt(x.id)),0),wDebt=db.workers.reduce((s,x)=>s+Math.max(0,workerBalance(x.id)),0);$('#dashboardCards').innerHTML=stat('رزرو این ماه',fmt(booked))+stat('کل دریافتی',money(recv))+stat('مطالبات بانی‌ها',money(sDebt))+stat('بدهی عوامل',money(wDebt));const today=todayJ(),up=db.rozehs.map(r=>{const dates=[...(r.dates||[])].sort(compareJ),future=dates.filter(d=>compareJ(d,today)>=0);return {r,dates,future,next:future[0]||''}}).filter(x=>x.future.length).sort((a,b)=>compareJ(a.next,b.next)).slice(0,6);$('#upcomingList').innerHTML=up.length?up.map(x=>rozehRow(x.r,dateRangeLabel(x.dates))).join(''):'<p class="muted">مراسم آینده‌ای ثبت نشده است.</p>';bindRozehRows()}
function dateRangeLabel(dates){const ds=[...(dates||[])].filter(Boolean).sort(compareJ);if(!ds.length)return 'بدون تاریخ';if(ds.length===1)return `تاریخ ${ds[0]}`;return `از تاریخ ${ds[0]} تا تاریخ ${ds[ds.length-1]}`}
function rozehRow(r,date){const s=sponsorBy(r.sponsorId),due=sponsorCharge(r);return `<button class="list-item rozeh-open" data-id="${r.id}" style="width:100%;text-align:right"><div class="main"><h3>${esc(s?.name||'بانی نامشخص')}</h3><p>${esc(date||r.dates?.join('، '))}${r.time?' • '+esc(r.time):''}${r.place?' • '+esc(r.place):''}</p><span class="badge red">رزرو شده</span></div><div class="amount">${money(due)}<p>${(r.expenses||[]).length} ردیف هزینه</p></div></button>`}
function renderRozehs(filter=''){const f=filter.trim(),items=[...db.rozehs].filter(r=>{const s=sponsorBy(r.sponsorId);const txt=[s?.name,r.place,r.type,(r.dates||[]).join(' ')].join(' ');return !f||txt.includes(f)}).sort((a,b)=>compareJ(a.dates?.[0]||'9999/01/01',b.dates?.[0]||'9999/01/01'));$('#rozehList').innerHTML=items.length?items.map(r=>rozehRow(r,r.dates.join('، '))).join(''):'<div class="card"><p class="muted">موردی پیدا نشد.</p></div>';bindRozehRows()}
function bindRozehRows(){$$('.rozeh-open').forEach(x=>x.onclick=()=>openRozeh(x.dataset.id))}
function renderSponsors(filter=''){const f=filter.trim(),items=db.sponsors.filter(s=>!f||s.name.includes(f)||(s.phone||'').includes(f));$('#sponsorList').innerHTML=items.length?items.map(s=>`<button class="list-item sponsor-open" data-id="${s.id}" style="width:100%;text-align:right"><div class="main"><h3>${esc(s.name)}</h3><p>${esc(s.phone||'بدون شماره')} • ${db.rozehs.filter(r=>r.sponsorId===s.id).length} مراسم</p></div><div class="amount ${sponsorDebt(s.id)>0?'debt':'credit'}">${money(Math.abs(sponsorDebt(s.id)))}<p>${sponsorDebt(s.id)>0?'بدهکار':'تسویه/بستانکار'}</p></div></button>`).join(''):'<p class="muted">بانی‌ای پیدا نشد.</p>';$$('.sponsor-open').forEach(x=>x.onclick=()=>openSponsor(x.dataset.id))}
function renderWorkers(filter=''){const f=filter.trim(),items=db.workers.filter(w=>!f||[w.name,w.role,w.phone].join(' ').includes(f));$('#workerList').innerHTML=items.length?items.map(w=>`<button class="list-item worker-open" data-id="${w.id}" style="width:100%;text-align:right"><div class="main"><h3>${esc(w.name)}</h3><p>${esc(w.role)} • ${esc(w.phone||'بدون شماره')}</p></div><div class="amount ${workerBalance(w.id)>0?'debt':'credit'}">${money(Math.abs(workerBalance(w.id)))}</div></button>`).join(''):'<p class="muted">عاملی ثبت نشده.</p>';$$('.worker-open').forEach(x=>x.onclick=()=>openWorker(x.dataset.id))}
function renderAccounting(){const recv=db.transactions.filter(t=>t.kind==='receive').reduce((s,t)=>s+Number(t.amount||0),0),paid=db.transactions.filter(t=>t.kind==='pay').reduce((s,t)=>s+Number(t.amount||0),0);$('#accountSummary').innerHTML=stat('دریافتی',money(recv))+stat('پرداختی',money(paid))+stat('طلب از بانی',money(db.sponsors.reduce((s,x)=>s+Math.max(0,sponsorDebt(x.id)),0)))+stat('طلب عوامل',money(db.workers.reduce((s,x)=>s+Math.max(0,workerBalance(x.id)),0)));$$('.seg').forEach(b=>b.classList.toggle('active',b.dataset.accountTab===accountTab));if(accountTab==='sponsors')$('#accountList').innerHTML=db.sponsors.map(s=>accountRow('sponsor',s.id,s.name,sponsorDebt(s.id))).join('')||'<p class="muted">بانی ثبت نشده.</p>';else if(accountTab==='workers')$('#accountList').innerHTML=db.workers.map(w=>accountRow('worker',w.id,w.name,workerBalance(w.id))).join('')||'<p class="muted">عامل ثبت نشده.</p>';else $('#accountList').innerHTML=[...db.transactions].sort((a,b)=>compareJ(b.date,a.date)).map(transactionRow).join('')||'<p class="muted">سندی ثبت نشده.</p>';$$('.account-party').forEach(x=>x.onclick=()=>openLedger(x.dataset.type,x.dataset.id));$$('.tx-delete').forEach(x=>x.onclick=e=>{e.stopPropagation();deleteTransaction(x.dataset.id)});$$('.tx-edit').forEach(x=>x.onclick=e=>{e.stopPropagation();editTransaction(x.dataset.id)})}
function accountRow(type,id,name,balance){return `<button class="list-item account-party" data-type="${type}" data-id="${id}" style="width:100%;text-align:right"><div><h3>${esc(name)}</h3><p>${type==='sponsor'?'مانده حساب بانی':'مانده قابل پرداخت'}</p></div><div class="amount ${balance>0?'debt':'credit'}">${money(Math.abs(balance))}</div></button>`}
function transactionRow(t){const p=t.partyType==='sponsor'?sponsorBy(t.partyId):workerBy(t.partyId);return `<div class="list-item"><div class="main"><h3>${t.kind==='receive'?'دریافت از':'پرداخت به'} ${esc(p?.name||'نامشخص')}</h3><p>${esc(t.date)} • ${esc(t.method||'')}${t.note?' • '+esc(t.note):''}</p></div><div><b class="amount ${t.kind==='receive'?'credit':'debt'}">${money(t.amount)}</b><button class="text-btn tx-edit" data-id="${t.id}">ویرایش</button><button class="text-btn danger-text tx-delete" data-id="${t.id}">حذف</button></div></div>`}
function renderOccasions(){const items=[...db.occasions].sort((a,b)=>(a.month||99)-(b.month||99)||(a.day||99)-(b.day||99));$('#occasionList').innerHTML=items.length?items.map(o=>`<div class="list-item"><div><h3>${esc(o.title)}</h3><p>${o.fixed?`${fmt(o.month)}/${fmt(o.day)} هر سال`:esc(o.date||'')}</p></div>${o.id.startsWith('fx')?'':`<div><button class="text-btn occasion-edit" data-id="${o.id}">ویرایش</button><button class="text-btn danger-text occasion-delete" data-id="${o.id}">حذف</button></div>`}</div>`).join(''):'<p class="muted">مناسبتی ثبت نشده.</p>';$$('.occasion-delete').forEach(b=>b.onclick=()=>{if(!confirm('این مناسبت حذف شود؟'))return;db.occasions=db.occasions.filter(x=>x.id!==b.dataset.id);save('حذف یک مناسبت');toast('مناسبت حذف شد')});$$('.occasion-edit').forEach(b=>b.onclick=()=>editOccasion(b.dataset.id))}
function renderAudit(){const el=$('#auditList');el.innerHTML=db.audit.length?db.audit.slice(0,30).map(a=>`<div class="list-item"><div><h3>${esc(a.text)}</h3><span class="audit-time">${new Date(a.at).toLocaleString('fa-IR')}</span></div></div>`).join(''):'<p class="muted">هنوز عملیاتی ثبت نشده است.</p>'}
function renderSettings(){$('#settingBankCard').value=db.settings.bankCard||'';$('#settingBankSheba').value=db.settings.bankSheba||'';$('#settingOrg').value=db.settings.org||'مدیریت روضه';$('#settingCurrency').value=db.settings.currency||'ریال';$('#settingPin').value=db.settings.pin||'';$('#settingReminder').value=db.settings.reminder||'0';$('#orgTitle').textContent=db.settings.org||'مدیریت روضه';$('#lockOrg').textContent=db.settings.org||'مدیریت روضه'}
function renderAll(){renderCalendar();renderDashboard();renderRozehs($('#rozehSearch')?.value||'');renderSponsors($('#sponsorSearch')?.value||'');renderWorkers($('#workerSearch')?.value||'');renderAccounting();renderOccasions();renderAudit();renderSettings()}

function dayClicked(date){const r=db.rozehs.find(x=>(x.dates||[]).includes(date));if(r)openRozeh(r.id);else addRozeh(date)}
function addSponsor(){openModal(`${modalHead('ثبت بانی')}<div class="field"><label>نام و نام خانوادگی *</label><input id="spName"></div><div class="two-cols"><div class="field"><label>شماره تماس</label><input id="spPhone" inputmode="tel"></div><div class="field"><label>شماره دوم</label><input id="spPhone2" inputmode="tel"></div></div><div class="field"><label>آدرس</label><textarea id="spAddress"></textarea></div><div class="field"><label>توضیحات</label><textarea id="spNote"></textarea></div><div class="form-actions"><button type="button" class="secondary close-btn">انصراف</button><button type="button" id="saveSponsor" class="primary">ثبت</button></div>`);$('#saveSponsor').onclick=()=>{const name=$('#spName').value.trim();if(!name)return toast('نام بانی را وارد کنید');db.sponsors.push({id:uid(),name,phone:$('#spPhone').value.trim(),phone2:$('#spPhone2').value.trim(),address:$('#spAddress').value.trim(),note:$('#spNote').value.trim()});save(`ثبت بانی: ${name}`);$('#modal').close();toast('بانی ثبت شد')}}
function editSponsor(id){const s=sponsorBy(id);openModal(`${modalHead('ویرایش بانی')}<div class="field"><label>نام</label><input id="spName" value="${esc(s.name)}"></div><div class="two-cols"><div class="field"><label>شماره تماس</label><input id="spPhone" value="${esc(s.phone||'')}"></div><div class="field"><label>شماره دوم</label><input id="spPhone2" value="${esc(s.phone2||'')}"></div></div><div class="field"><label>آدرس</label><textarea id="spAddress">${esc(s.address||'')}</textarea></div><div class="field"><label>توضیحات</label><textarea id="spNote">${esc(s.note||'')}</textarea></div><button type="button" id="saveSponsorEdit" class="primary full">ذخیره</button>`);$('#saveSponsorEdit').onclick=()=>{s.name=$('#spName').value.trim();s.phone=$('#spPhone').value.trim();s.phone2=$('#spPhone2').value.trim();s.address=$('#spAddress').value.trim();s.note=$('#spNote').value.trim();save(`ویرایش بانی: ${s.name}`);$('#modal').close();toast('ذخیره شد')}}
function addWorker(){openModal(`${modalHead('ثبت عامل')}<div class="field"><label>نام *</label><input id="wName"></div><div class="field"><label>نوع فعالیت</label><select id="wRole"><option>روحانی</option><option>مداح</option><option>عامل اجرایی</option><option>سایر</option></select></div><div class="two-cols"><div class="field"><label>شماره تماس</label><input id="wPhone"></div><div class="field"><label>مبلغ پیش‌فرض</label><input id="wRate" type="number"></div></div><div class="field"><label>شماره کارت / توضیحات</label><textarea id="wNote"></textarea></div><button type="button" id="saveWorker" class="primary full">ثبت عامل</button>`);$('#saveWorker').onclick=()=>{const name=$('#wName').value.trim();if(!name)return toast('نام را وارد کنید');db.workers.push({id:uid(),name,role:$('#wRole').value,phone:$('#wPhone').value.trim(),rate:Number($('#wRate').value)||0,note:$('#wNote').value.trim()});save(`ثبت عامل: ${name}`);$('#modal').close();toast('عامل ثبت شد')}}

function editWorker(id){const w=workerBy(id);if(!w)return;openModal(`${modalHead('ویرایش عامل')}<div class="field"><label>نام *</label><input id="wName" value="${esc(w.name)}"></div><div class="field"><label>نوع فعالیت</label><select id="wRole"><option>روحانی</option><option>مداح</option><option>عامل اجرایی</option><option>سایر</option></select></div><div class="two-cols"><div class="field"><label>شماره تماس</label><input id="wPhone" value="${esc(w.phone||'')}"></div><div class="field"><label>مبلغ پیش‌فرض</label><input id="wRate" type="number" value="${Number(w.rate)||0}"></div></div><div class="field"><label>شماره کارت / توضیحات</label><textarea id="wNote">${esc(w.note||'')}</textarea></div><button type="button" id="saveWorkerEdit" class="primary full">ذخیره تغییرات</button>`);$('#wRole').value=w.role||'سایر';$('#saveWorkerEdit').onclick=()=>{const name=$('#wName').value.trim();if(!name)return toast('نام را وارد کنید');w.name=name;w.role=$('#wRole').value;w.phone=$('#wPhone').value.trim();w.rate=Number($('#wRate').value)||0;w.note=$('#wNote').value.trim();save(`ویرایش عامل: ${name}`);$('#modal').close();toast('عامل ویرایش شد')}}
function deleteWorker(id){const w=workerBy(id);if(!w)return;const used=db.rozehs.some(r=>(r.expenses||[]).some(e=>e.workerId===id)),hasTx=db.transactions.some(t=>t.partyType==='worker'&&t.partyId===id);if(used||hasTx)return toast('این عامل سابقه مالی/مراسم دارد؛ ابتدا وابستگی‌ها را حذف کنید');if(confirm(`عامل «${w.name}» حذف شود؟`)){db.workers=db.workers.filter(x=>x.id!==id);save(`حذف عامل: ${w.name}`);$('#modal').close();toast('عامل حذف شد')}}
function deleteSponsor(id){const sp=sponsorBy(id);if(!sp)return;const used=db.rozehs.some(r=>r.sponsorId===id),hasTx=db.transactions.some(t=>t.partyType==='sponsor'&&t.partyId===id);if(used||hasTx)return toast('این بانی مراسم یا سند مالی دارد؛ ابتدا موارد وابسته را حذف کنید');if(confirm(`بانی «${sp.name}» حذف شود؟`)){db.sponsors=db.sponsors.filter(x=>x.id!==id);save(`حذف بانی: ${sp.name}`);$('#modal').close();toast('بانی حذف شد')}}
function renderRozehDatePicker(selected,pickerState,excludeRozehId=''){
 const title=$('#rPickerTitle'),grid=$('#rPickerGrid'),summary=$('#rSelectedDates');if(!title||!grid)return;
 title.textContent=`${jMonths[pickerState.month-1]} ${fmt(pickerState.year)}`;grid.innerHTML='';
 const gd=toGregorian(pickerState.year,pickerState.month,1),offset=(new Date(gd.gy,gd.gm-1,gd.gd).getDay()+1)%7;
 for(let i=0;i<offset;i++)grid.insertAdjacentHTML('beforeend','<div class="picker-day empty"></div>');
 for(let d=1;d<=jDaysInMonth(pickerState.year,pickerState.month);d++){
  const key=jKey(pickerState.year,pickerState.month,d),booked=db.rozehs.some(r=>r.id!==excludeRozehId&&(r.dates||[]).includes(key)),isSelected=selected.has(key),occ=occasionFor(pickerState.year,pickerState.month,d);
  grid.insertAdjacentHTML('beforeend',`<button type="button" class="picker-day ${booked?'booked':''} ${isSelected?'selected':''} ${!booked&&occ?'occasion':''}" data-pick-date="${key}" ${booked?'disabled':''}><span>${fmt(d)}</span>${booked?'<small>رزرو</small>':isSelected?'<small>انتخاب شد</small>':occ?`<small>${esc(occ)}</small>`:''}</button>`);
 }
 $$('.picker-day[data-pick-date]').forEach(b=>b.onclick=()=>{const key=b.dataset.pickDate;if(selected.has(key))selected.delete(key);else selected.add(key);renderRozehDatePicker(selected,pickerState)});
 const dates=[...selected].sort(compareJ);summary.innerHTML=dates.length?dates.map(d=>`<span class="selected-date-chip">${esc(d)}</span>`).join(''):'<span class="muted tiny">هنوز روزی انتخاب نشده است.</span>';
 $('#rDateCount').textContent=dates.length?`${fmt(dates.length)} روز انتخاب شده`:'انتخاب روز از تقویم';
}
function addRozeh(prefill=''){
 if(!db.sponsors.length){toast('ابتدا یک بانی ثبت کنید');return addSponsor()}
 const opts=db.sponsors.map(s=>`<option value="${s.id}">${esc(s.name)}${s.phone?' - '+esc(s.phone):''}</option>`).join('');
 const selected=new Set(validJ(prefill)?[prefill]:[]),base=parseJ(validJ(prefill)?prefill:todayJ()),pickerState={year:base.y,month:base.m};
 openModal(`${modalHead('ثبت روضه')}<div class="field"><label>بانی *</label><select id="rSponsor">${opts}</select></div><div class="field"><label>تاریخ یا چند تاریخ *</label><button type="button" id="toggleDatePicker" class="date-picker-trigger"><span id="rDateCount">انتخاب روز از تقویم</span><b>▾</b></button><div id="rSelectedDates" class="selected-dates"></div><div id="rDatePicker" class="inline-date-picker"><div class="picker-head"><button type="button" id="rPickerNext" class="nav-btn mini">‹</button><strong id="rPickerTitle"></strong><button type="button" id="rPickerPrev" class="nav-btn mini">›</button></div><div class="picker-weekdays"><span>ش</span><span>ی</span><span>د</span><span>س</span><span>چ</span><span>پ</span><span>ج</span></div><div id="rPickerGrid" class="picker-grid"></div><p class="muted tiny">روزهای قرمزِ قفل‌دار قبلاً رزرو شده‌اند. هر روزی که انتخاب کنی قرمز می‌شود؛ برای حذف انتخاب، دوباره همان روز را لمس کن.</p></div></div><div class="two-cols"><div class="field"><label>ساعت</label><input id="rTime" type="time"></div><div class="field"><label>نوع مراسم</label><input id="rType" value="روضه"></div></div><div class="field"><label>محل برگزاری</label><input id="rPlace"></div><div class="field"><label>مبلغ توافقی بانی</label><input id="rCharge" type="number" placeholder="صفر = جمع هزینه‌ها"></div><div class="field"><label>توضیحات</label><textarea id="rNote"></textarea></div><button type="button" id="saveRozeh" class="primary full">ثبت و قفل تاریخ‌ها</button>`);
 const picker=$('#rDatePicker');picker.classList.toggle('open',!!prefill);renderRozehDatePicker(selected,pickerState);
 $('#toggleDatePicker').onclick=()=>picker.classList.toggle('open');
 $('#rPickerPrev').onclick=()=>{pickerState.month--;if(pickerState.month<1){pickerState.month=12;pickerState.year--}renderRozehDatePicker(selected,pickerState)};
 $('#rPickerNext').onclick=()=>{pickerState.month++;if(pickerState.month>12){pickerState.month=1;pickerState.year++}renderRozehDatePicker(selected,pickerState)};
 $('#saveRozeh').onclick=()=>{const dates=[...selected].sort(compareJ);if(!dates.length)return toast('حداقل یک روز را از تقویم انتخاب کنید');const conflict=dates.find(d=>db.rozehs.some(r=>(r.dates||[]).includes(d)));if(conflict)return toast(`تاریخ ${conflict} قبلاً رزرو شده`);const r={id:uid(),sponsorId:$('#rSponsor').value,dates,time:$('#rTime').value,type:$('#rType').value.trim(),place:$('#rPlace').value.trim(),sponsorCharge:Number($('#rCharge').value)||0,note:$('#rNote').value.trim(),expenses:[],createdAt:new Date().toISOString()};db.rozehs.push(r);save(`ثبت روضه برای ${sponsorBy(r.sponsorId)?.name||''} در ${dates.join('، ')}`);$('#modal').close();toast('رزرو ثبت و تاریخ قفل شد')}
}

function editRozeh(id){const r=rozehBy(id);if(!r)return;const opts=db.sponsors.map(sp=>`<option value="${sp.id}">${esc(sp.name)}</option>`).join(''),selected=new Set(r.dates||[]),base=parseJ((r.dates||[])[0]||todayJ()),pickerState={year:base.y,month:base.m};openModal(`${modalHead('ویرایش روضه')}<div class="field"><label>بانی *</label><select id="rSponsor">${opts}</select></div><div class="field"><label>تاریخ‌ها *</label><button type="button" id="toggleDatePicker" class="date-picker-trigger"><span id="rDateCount"></span><b>▾</b></button><div id="rSelectedDates" class="selected-dates"></div><div id="rDatePicker" class="inline-date-picker open"><div class="picker-head"><button type="button" id="rPickerNext" class="nav-btn mini">‹</button><strong id="rPickerTitle"></strong><button type="button" id="rPickerPrev" class="nav-btn mini">›</button></div><div class="picker-weekdays"><span>ش</span><span>ی</span><span>د</span><span>س</span><span>چ</span><span>پ</span><span>ج</span></div><div id="rPickerGrid" class="picker-grid"></div><p class="muted tiny">تاریخ‌های همین روضه قابل تغییرند؛ رزروهای دیگر قفل هستند.</p></div></div><div class="two-cols"><div class="field"><label>ساعت</label><input id="rTime" type="time" value="${esc(r.time||'')}"></div><div class="field"><label>نوع مراسم</label><input id="rType" value="${esc(r.type||'روضه')}"></div></div><div class="field"><label>محل</label><input id="rPlace" value="${esc(r.place||'')}"></div><div class="field"><label>مبلغ توافقی بانی</label><input id="rCharge" type="number" value="${Number(r.sponsorCharge)||0}"></div><div class="field"><label>توضیحات</label><textarea id="rNote">${esc(r.note||'')}</textarea></div><button type="button" id="saveRozehEdit" class="primary full">ذخیره تغییرات</button>`);$('#rSponsor').value=r.sponsorId;const picker=$('#rDatePicker');renderRozehDatePicker(selected,pickerState,id);$('#toggleDatePicker').onclick=()=>picker.classList.toggle('open');$('#rPickerPrev').onclick=()=>{pickerState.month--;if(pickerState.month<1){pickerState.month=12;pickerState.year--}renderRozehDatePicker(selected,pickerState,id)};$('#rPickerNext').onclick=()=>{pickerState.month++;if(pickerState.month>12){pickerState.month=1;pickerState.year++}renderRozehDatePicker(selected,pickerState,id)};$('#saveRozehEdit').onclick=()=>{const dates=[...selected].sort(compareJ);if(!dates.length)return toast('حداقل یک روز انتخاب کنید');const conflict=dates.find(d=>db.rozehs.some(x=>x.id!==id&&(x.dates||[]).includes(d)));if(conflict)return toast(`تاریخ ${conflict} قبلاً رزرو شده`);r.sponsorId=$('#rSponsor').value;r.dates=dates;r.time=$('#rTime').value;r.type=$('#rType').value.trim()||'روضه';r.place=$('#rPlace').value.trim();r.sponsorCharge=Number($('#rCharge').value)||0;r.note=$('#rNote').value.trim();save(`ویرایش روضه ${dates.join('، ')}`);$('#modal').close();toast('روضه ویرایش شد')}}
function openRozeh(id){const r=rozehBy(id);if(!r)return;const sp=sponsorBy(r.sponsorId);const exp=(r.expenses||[]).map(e=>`<div class="list-item"><div class="main"><h3>${esc(e.title)}</h3><p>${fmt(e.qty)} × ${money(e.amount)}${e.workerId?' • '+esc(workerBy(e.workerId)?.name||''):''}${e.workerId?' • '+(e.attended===false?'غایب':'حاضر'):''}</p></div><div><b>${money((Number(e.qty)||0)*(Number(e.amount)||0))}</b><div><button class="text-btn exp-edit" data-id="${e.id}">ویرایش</button><button class="text-btn danger-text exp-delete" data-id="${e.id}">حذف</button></div></div></div>`).join('');openModal(`${modalHead('پرونده روضه')}<div class="detail-grid"><div class="detail-box"><span>بانی</span><b>${esc(sp?.name||'—')}</b></div><div class="detail-box"><span>تاریخ</span><b>${esc(r.dates.join('، '))}</b></div><div class="detail-box"><span>ساعت</span><b>${esc(r.time||'—')}</b></div><div class="detail-box"><span>محل</span><b>${esc(r.place||'—')}</b></div><div class="detail-box"><span>جمع هزینه</span><b>${money(expenseTotal(r))}</b></div><div class="detail-box"><span>قابل دریافت از بانی</span><b>${money(sponsorCharge(r))}</b></div></div><div class="section-title" style="margin-top:14px"><h2>ریز هزینه و حضور</h2><button type="button" id="addExpense" class="primary small">افزودن</button></div><div class="list">${exp||'<p class="muted">هزینه‌ای ثبت نشده.</p>'}</div>${r.note?`<p class="muted">${esc(r.note)}</p>`:''}<div class="grid-actions"><button type="button" id="invoiceRozeh" class="primary">صورتحساب بانی</button><button type="button" id="editRozehBtn" class="secondary">ویرایش روضه</button><button type="button" id="receiveThis" class="secondary">دریافت وجه</button><button type="button" id="duplicateRozeh" class="secondary">کپی مراسم</button><button type="button" id="deleteRozeh" class="danger">حذف رزرو</button></div>`);$('#invoiceRozeh').onclick=()=>openSponsorInvoice(r.sponsorId,id);$('#addExpense').onclick=()=>addExpense(id);$('#editRozehBtn').onclick=()=>editRozeh(id);$('#receiveThis').onclick=()=>addTransaction('sponsor',r.sponsorId,'receive',id);$('#duplicateRozeh').onclick=()=>addRozeh();$('#deleteRozeh').onclick=()=>{if(confirm('رزرو و هزینه‌های وابسته و سندهای متصل حذف شود؟')){db.rozehs=db.rozehs.filter(x=>x.id!==id);db.transactions=db.transactions.filter(t=>t.rozehId!==id);save(`حذف رزرو ${r.dates.join('، ')}`);$('#modal').close();toast('رزرو حذف شد')}};$$('.exp-delete').forEach(b=>b.onclick=()=>{if(!confirm('این ردیف هزینه حذف شود؟'))return;r.expenses=r.expenses.filter(e=>e.id!==b.dataset.id);save('حذف ردیف هزینه از مراسم');$('#modal').close();setTimeout(()=>openRozeh(id),20)});$$('.exp-edit').forEach(b=>b.onclick=()=>editExpense(id,b.dataset.id))}

function addExpense(rozehId){const r=rozehBy(rozehId),opts='<option value="">بدون عامل مشخص</option>'+db.workers.map(w=>`<option value="${w.id}" data-rate="${w.rate||0}">${esc(w.name)} - ${esc(w.role)}</option>`).join('');openModal(`${modalHead('افزودن هزینه')}<div class="field"><label>عنوان</label><select id="eTitle"><option>روحانی</option><option>مداح</option><option>عوامل اجرایی</option><option>قهوه</option><option>حسینیه</option><option>هزینه پیش‌بینی‌نشده</option><option>سایر</option></select></div><div class="field" id="eCustomTitleWrap" style="display:none"><label>نام هزینه جدید *</label><input id="eCustomTitle" placeholder="مثلاً گل، غذا، حمل‌ونقل، صوت و ..."></div><div class="field"><label>عامل مرتبط</label><select id="eWorker">${opts}</select></div><div class="two-cols"><div class="field"><label>تعداد</label><input id="eQty" type="number" min="1" value="1"></div><div class="field"><label>مبلغ واحد</label><input id="eAmount" type="number"></div></div><label class="check-row"><input id="eAttend" type="checkbox" checked> حضور عامل ثبت شده است</label><div class="field"><label>توضیحات</label><input id="eNote"></div><button type="button" id="saveExpense" class="primary full">ثبت هزینه</button>`);const syncCustomTitle=()=>{const other=$('#eTitle').value==='سایر';$('#eCustomTitleWrap').style.display=other?'block':'none';if(other)setTimeout(()=>$('#eCustomTitle').focus(),0)};$('#eTitle').onchange=syncCustomTitle;$('#eWorker').onchange=()=>{const o=$('#eWorker').selectedOptions[0],w=workerBy($('#eWorker').value);if(o?.dataset.rate)$('#eAmount').value=o.dataset.rate;if(w){$('#eTitle').value=w.role==='عامل اجرایی'?'عوامل اجرایی':w.role;syncCustomTitle()}};$('#saveExpense').onclick=()=>{const qty=Number($('#eQty').value)||1,amount=Number($('#eAmount').value)||0,title=$('#eTitle').value==='سایر'?$('#eCustomTitle').value.trim():$('#eTitle').value;if(!title)return toast('نام هزینه جدید را وارد کنید');if(amount<0)return toast('مبلغ صحیح نیست');r.expenses.push({id:uid(),title,workerId:$('#eWorker').value||'',qty,amount,attended:$('#eAttend').checked,note:$('#eNote').value.trim()});save(`ثبت هزینه ${title} برای مراسم`);$('#modal').close();setTimeout(()=>openRozeh(rozehId),20)}}
function editExpense(rozehId,expenseId){const r=rozehBy(rozehId),e=(r?.expenses||[]).find(x=>x.id===expenseId);if(!e)return;const opts='<option value="">بدون عامل مشخص</option>'+db.workers.map(w=>`<option value="${w.id}">${esc(w.name)} - ${esc(w.role)}</option>`).join('');openModal(`${modalHead('ویرایش هزینه')}<div class="field"><label>عنوان هزینه</label><input id="eeTitle" value="${esc(e.title)}"></div><div class="field"><label>عامل مرتبط</label><select id="eeWorker">${opts}</select></div><div class="two-cols"><div class="field"><label>تعداد</label><input id="eeQty" type="number" min="1" value="${Number(e.qty)||1}"></div><div class="field"><label>مبلغ واحد</label><input id="eeAmount" type="number" value="${Number(e.amount)||0}"></div></div><label class="check-row"><input id="eeAttend" type="checkbox" ${e.attended===false?'':'checked'}> حضور عامل ثبت شده است</label><div class="field"><label>توضیحات</label><input id="eeNote" value="${esc(e.note||'')}"></div><button type="button" id="saveExpenseEdit" class="primary full">ذخیره تغییرات</button>`);$('#eeWorker').value=e.workerId||'';$('#saveExpenseEdit').onclick=()=>{const title=$('#eeTitle').value.trim(),qty=Number($('#eeQty').value)||1,amount=Number($('#eeAmount').value)||0;if(!title)return toast('عنوان هزینه را وارد کنید');if(qty<1||amount<0)return toast('تعداد یا مبلغ صحیح نیست');e.title=title;e.workerId=$('#eeWorker').value||'';e.qty=qty;e.amount=amount;e.attended=$('#eeAttend').checked;e.note=$('#eeNote').value.trim();save(`ویرایش هزینه ${title}`);$('#modal').close();setTimeout(()=>openRozeh(rozehId),20)}}

function editCharge(id){const r=rozehBy(id),v=prompt(`مبلغ قابل دریافت از بانی (${db.settings.currency})\nصفر = محاسبه خودکار از جمع هزینه‌ها`,r.sponsorCharge||0);if(v===null)return;r.sponsorCharge=Number(v)||0;save('ویرایش مبلغ قابل دریافت از بانی');$('#modal').close();setTimeout(()=>openRozeh(id),20)}

// Sponsor-facing statement: never include worker records or private notes.
function invoiceTitle(e){
 let title=String(e.title||'هزینه').trim();
 const names=[...db.workers,...db.sponsors].map(x=>String(x.name||'').trim()).filter(Boolean).sort((a,b)=>b.length-a.length);
 names.forEach(name=>{title=title.split(name).join('')});
 return title.replace(/\s+/g,' ').replace(/^[\s:،()\-–]+|[\s:،()\-–]+$/g,'').trim()||'هزینه';
}
function sponsorStatement(id){
 const rs=db.rozehs.filter(r=>r.sponsorId===id),lines=['صورتحساب هزینه‌های مراسم'],groups=new Map();
 const dates=[...new Set(rs.flatMap(r=>r.dates||[]))].sort(compareJ);
 if(dates.length)lines.push('تاریخ مراسم: '+dates.join('، '));
 let cost=0;
 rs.forEach(r=>(r.expenses||[]).forEach(e=>{
  let title=invoiceTitle(e).replace(/ي/g,'ی').replace(/ك/g,'ک');
  if(title==='عامل اجرایی')title='عوامل اجرایی';
  const qty=Number(e.qty)||0,amount=qty*(Number(e.amount)||0),g=groups.get(title)||{qty:0,amount:0};
  g.qty+=qty;g.amount+=amount;groups.set(title,g);cost+=amount;
 }));
 groups.forEach((g,title)=>lines.push(`${title} (${fmt(g.qty)} ${['عوامل اجرایی','روحانی','مداح'].includes(title)?'نفر':'عدد'}): ${money(g.amount)}`));
 if(!groups.size)lines.push('هزینه‌ای ثبت نشده است.');
 lines.push('','جمع کل هزینه‌ها: '+money(cost));
 if(db.settings.bankCard)lines.push('','شماره کارت حسینیه:',db.settings.bankCard);
 if(db.settings.bankSheba)lines.push('','شماره شبای حسینیه:',db.settings.bankSheba);
 return lines.join('\n');
}
function ceremonyName(r){return r.name||r.title||`${r.type||'روضه'} — ${sponsorBy(r.sponsorId)?.name||'بانی نامشخص'}`}
function openAllExpenseDetails(){openModal(`${modalHead('ریز همه هزینه‌ها')}<div class="list">${expenseDetailsHTML()}</div>`)}
function expenseDetailsHTML(workerId=''){
 const rows=[];
 db.rozehs.forEach(r=>(r.expenses||[]).forEach(e=>{if(!workerId||e.workerId===workerId)rows.push({r,e})}));
 rows.sort((a,b)=>compareJ((b.r.dates||[])[0],(a.r.dates||[])[0]));
 return rows.map(({r,e})=>`<div class="list-item"><div class="main"><h3>${esc(ceremonyName(r))}</h3><p>تاریخ: ${esc((r.dates||[]).join('، '))}</p><p>${esc(e.title)} • ${fmt(e.qty)} × ${money(e.amount)}</p>${r.place?`<p>محل: ${esc(r.place)}</p>`:''}${e.note?`<p>${esc(e.note)}</p>`:''}${workerId&&e.attended===false?'<p>غایب — منظورشده در حق‌الزحمه: صفر</p>':''}</div><b>${money((Number(e.qty)||0)*(Number(e.amount)||0))}</b></div>`).join('')||'<p class="muted">هزینه‌ای ثبت نشده است.</p>';
}
function workerStatement(id){
 const w=workerBy(id),lines=['صورتحساب عامل: '+(w?.name||'')];
 db.rozehs.forEach(r=>(r.expenses||[]).filter(e=>e.workerId===id).forEach(e=>{
  lines.push('',ceremonyName(r),'تاریخ: '+(r.dates||[]).join('، '),`${e.title}: ${fmt(e.qty)} × ${money(e.amount)} = ${money((Number(e.qty)||0)*(Number(e.amount)||0))}`);
  if(e.attended===false)lines.push('غایب — منظورشده در حق‌الزحمه: صفر');
 }));
 lines.push('','جمع حق‌الزحمه: '+money(workerDue(id)),'پرداخت‌شده: '+money(workerPaid(id)),'مانده: '+money(workerBalance(id)));
 return lines.join('\n');
}
function openWorkerStatement(id){
 openModal(`${modalHead('صورتحساب تفصیلی عامل')}<div class="field"><textarea id="workerStatementText" readonly style="min-height:350px;line-height:2">${esc(workerStatement(id))}</textarea></div><button id="copyWorkerStatement" class="primary full">کپی صورتحساب</button><button id="backWorkerStatement" class="secondary full">بازگشت</button>`);
 $('#copyWorkerStatement').onclick=async()=>{const f=$('#workerStatementText');try{await navigator.clipboard.writeText(f.value);toast('صورتحساب کپی شد')}catch{f.focus();f.select();try{if(document.execCommand('copy'))return toast('صورتحساب کپی شد')}catch{}toast('متن انتخاب شد؛ کپی کنید')}};
 $('#backWorkerStatement').onclick=()=>openWorker(id);
}
function invoicePhone(value){return String(value||'').replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/[\s()\-]/g,'')}
function openSponsorInvoice(id,returnRozehId=''){
 const sp=sponsorBy(id);if(!sp)return toast('بانی پیدا نشد');
 const text=sponsorStatement(id),phone=invoicePhone(sp.phone||sp.phone2);
 openModal(`${modalHead('صورتحساب بانی')}<p class="muted">ریز هزینه‌های همه مراسم این بانی؛ بدون نام افراد و توضیحات داخلی.</p>${!db.settings.bankCard||!db.settings.bankSheba?'<p class="muted">برای اضافه شدن کارت و شبا، آن‌ها را یک‌بار در تنظیمات ثبت کنید.</p>':''}<div class="field"><label for="sponsorInvoiceText">متن آماده پیامک</label><textarea id="sponsorInvoiceText" readonly dir="rtl" style="min-height:340px;line-height:2">${esc(text)}</textarea></div><p class="muted tiny">متن بلند ممکن است در چند پیامک ارسال شود. پیش از ارسال، متن و گیرنده را بررسی کنید.</p><div class="grid-actions"><button type="button" id="copySponsorInvoice" class="primary">کپی صورتحساب</button><button type="button" id="smsSponsorInvoice" class="secondary">باز کردن پیامک</button><button type="button" id="backSponsorInvoice" class="secondary">بازگشت به پرونده</button></div>`);
 $('#copySponsorInvoice').onclick=async()=>{
  try{if(!navigator.clipboard?.writeText)throw Error();await navigator.clipboard.writeText(text);toast('صورتحساب کپی شد')}
  catch{const field=$('#sponsorInvoiceText');field.focus();field.select();field.setSelectionRange(0,field.value.length);try{if(document.execCommand('copy'))return toast('صورتحساب کپی شد')}catch{}toast('متن انتخاب شد؛ گزینه کپی را بزنید')}
 };
 $('#smsSponsorInvoice').onclick=()=>{
  if(!/^\+?\d{7,15}$/.test(phone))return toast('ابتدا شماره تماس معتبر برای بانی ثبت کنید');
  const sep=/iPad|iPhone|iPod/.test(navigator.userAgent)?'&':'?';
  window.location.href=`sms:${phone}${sep}body=${encodeURIComponent(text)}`;
 };
 $('#backSponsorInvoice').onclick=()=>returnRozehId?openRozeh(returnRozehId):openSponsor(id);
}

function openSponsor(id){const s=sponsorBy(id),rs=db.rozehs.filter(r=>r.sponsorId===id),charge=rs.reduce((a,r)=>a+sponsorCharge(r),0),paid=sponsorPaid(id);openModal(`${modalHead('پرونده بانی')}<h2>${esc(s.name)}</h2><p class="muted">${esc(s.phone||'بدون شماره')}${s.phone2?' • '+esc(s.phone2):''}<br>${esc(s.address||'')}</p><div class="detail-grid"><div class="detail-box"><span>تعداد مراسم</span><b>${fmt(rs.length)}</b></div><div class="detail-box"><span>جمع بدهی</span><b>${money(charge)}</b></div><div class="detail-box"><span>دریافتی</span><b>${money(paid)}</b></div><div class="detail-box"><span>مانده</span><b>${money(sponsorDebt(id))}</b></div></div><div class="list">${rs.map(r=>rozehRow(r,r.dates.join('، '))).join('')||'<p class="muted">مراسمی ندارد.</p>'}</div><div class="grid-actions"><button type="button" id="invoiceSponsor" class="primary">صورتحساب بانی</button><button type="button" id="receiveSponsor" class="primary">دریافت وجه</button><button type="button" id="ledgerSponsor" class="secondary">گردش حساب</button><button type="button" id="editSponsorBtn" class="secondary">ویرایش</button><button type="button" id="deleteSponsorBtn" class="danger">حذف بانی</button></div>`);bindRozehRows();$('#invoiceSponsor').onclick=()=>openSponsorInvoice(id);$('#receiveSponsor').onclick=()=>addTransaction('sponsor',id,'receive');$('#ledgerSponsor').onclick=()=>openLedger('sponsor',id);$('#editSponsorBtn').onclick=()=>editSponsor(id);$('#deleteSponsorBtn').onclick=()=>deleteSponsor(id)}
function openWorker(id){const w=workerBy(id);if(!w)return;const jobs=[];db.rozehs.forEach(r=>(r.expenses||[]).forEach(e=>{if(e.workerId===id)jobs.push({r,e})}));openModal(`${modalHead('پرونده عامل')}<h2>${esc(w.name)}</h2><p class="muted">${esc(w.role)} • ${esc(w.phone||'بدون شماره')}<br>${esc(w.note||'')}</p><div class="detail-grid"><div class="detail-box"><span>حضور ثبت‌شده</span><b>${fmt(jobs.filter(x=>x.e.attended!==false).length)}</b></div><div class="detail-box"><span>جمع حق‌الزحمه</span><b>${money(workerDue(id))}</b></div><div class="detail-box"><span>پرداخت‌شده</span><b>${money(workerPaid(id))}</b></div><div class="detail-box"><span>مانده</span><b>${money(workerBalance(id))}</b></div></div><div class="list">${expenseDetailsHTML(id)}</div><div class="grid-actions"><button type="button" id="workerStatementBtn" class="primary">صورتحساب تفصیلی</button><button type="button" id="payWorker" class="primary">ثبت پرداخت</button><button type="button" id="ledgerWorker" class="secondary">گردش حساب</button><button type="button" id="editWorkerBtn" class="secondary">ویرایش عامل</button><button type="button" id="deleteWorkerBtn" class="danger">حذف عامل</button></div>`);$('#workerStatementBtn').onclick=()=>openWorkerStatement(id);$('#payWorker').onclick=()=>addTransaction('worker',id,'pay');$('#ledgerWorker').onclick=()=>openLedger('worker',id);$('#editWorkerBtn').onclick=()=>editWorker(id);$('#deleteWorkerBtn').onclick=()=>deleteWorker(id)}

function addTransaction(preType='',preId='',preKind='',rozehId=''){const sponsors=db.sponsors.map(s=>`<option value="sponsor:${s.id}">${esc(s.name)} (بانی)</option>`).join(''),workers=db.workers.map(w=>`<option value="worker:${w.id}">${esc(w.name)} (${esc(w.role)})</option>`).join('');openModal(`${modalHead('ثبت سند مالی')}<div class="field"><label>شخص</label><select id="tParty">${sponsors}${workers}</select></div><div class="field"><label>نوع سند</label><select id="tKind"><option value="receive">دریافت از بانی</option><option value="pay">پرداخت به عامل</option></select></div><div class="field"><label>مبلغ</label><input id="tAmount" type="number"></div><div class="two-cols"><div class="field"><label>تاریخ</label><input id="tDate" value="${todayJ()}"></div><div class="field"><label>روش</label><select id="tMethod"><option>کارت</option><option>نقدی</option><option>انتقال بانکی</option><option>سایر</option></select></div></div><div class="field"><label>شماره پیگیری / توضیحات</label><input id="tNote"></div><button type="button" id="saveTrans" class="primary full">ثبت سند</button>`);if(preType&&preId)$('#tParty').value=`${preType}:${preId}`;$('#tParty').onchange=()=>{$('#tKind').value=$('#tParty').value.startsWith('sponsor:')?'receive':'pay'};$('#tParty').dispatchEvent(new Event('change'));if(preKind)$('#tKind').value=preKind;$('#saveTrans').onclick=()=>{const amount=Number($('#tAmount').value)||0,date=$('#tDate').value;if(amount<=0)return toast('مبلغ را وارد کنید');if(!validJ(date))return toast('تاریخ صحیح نیست');const [partyType,partyId]=$('#tParty').value.split(':'),kind=$('#tKind').value;if((partyType==='sponsor'&&kind!=='receive')||(partyType==='worker'&&kind!=='pay'))return toast('نوع سند با شخص هماهنگ نیست');db.transactions.push({id:uid(),partyType,partyId,kind,amount,date,method:$('#tMethod').value,note:$('#tNote').value.trim(),rozehId:rozehId||''});save(`ثبت ${kind==='receive'?'دریافت':'پرداخت'} ${money(amount)}`);$('#modal').close();toast('سند ثبت شد')}}
function editTransaction(id){const t=db.transactions.find(x=>x.id===id);if(!t)return;openModal(`${modalHead('ویرایش سند مالی')}<div class="field"><label>مبلغ</label><input id="teAmount" type="number" value="${Number(t.amount)||0}"></div><div class="field"><label>تاریخ</label><input id="teDate" value="${esc(t.date)}"></div><div class="field"><label>روش</label><select id="teMethod"><option>کارت</option><option>نقدی</option><option>انتقال بانکی</option><option>سایر</option></select></div><div class="field"><label>توضیحات</label><input id="teNote" value="${esc(t.note||'')}"></div><button type="button" id="saveTxEdit" class="primary full">ذخیره تغییرات</button>`);$('#teMethod').value=t.method||'سایر';$('#saveTxEdit').onclick=()=>{const amount=Number($('#teAmount').value)||0,date=$('#teDate').value.trim();if(amount<=0)return toast('مبلغ صحیح نیست');if(!validJ(date))return toast('تاریخ صحیح نیست');t.amount=amount;t.date=date;t.method=$('#teMethod').value;t.note=$('#teNote').value.trim();save('ویرایش سند مالی');$('#modal').close();toast('سند ویرایش شد')}}
function deleteTransaction(id){const t=db.transactions.find(x=>x.id===id);if(!t||!confirm('این سند مالی حذف شود؟'))return;db.transactions=db.transactions.filter(x=>x.id!==id);save('حذف سند مالی');toast('سند حذف شد')}
function openLedger(type,id){const p=type==='sponsor'?sponsorBy(id):workerBy(id),tx=db.transactions.filter(t=>t.partyType===type&&t.partyId===id).sort((a,b)=>compareJ(b.date,a.date)),bal=type==='sponsor'?sponsorDebt(id):workerBalance(id);openModal(`${modalHead('گردش حساب')}<h2>${esc(p?.name||'')}</h2><div class="detail-box"><span>مانده فعلی</span><b>${money(bal)}</b></div>${type==='worker'?'<h3>ریز مراسم و هزینه‌ها</h3><div class="list">'+expenseDetailsHTML(id)+'</div>':''}<h3>دریافت و پرداخت</h3><div class="list">${tx.map(transactionRow).join('')||'<p class="muted">تراکنشی ثبت نشده.</p>'}</div><button type="button" id="ledgerAdd" class="primary full">ثبت ${type==='sponsor'?'دریافت':'پرداخت'}</button>`);$('#ledgerAdd').onclick=()=>addTransaction(type,id,type==='sponsor'?'receive':'pay');$$('.tx-delete').forEach(b=>b.onclick=()=>deleteTransaction(b.dataset.id));$$('.tx-edit').forEach(b=>b.onclick=()=>editTransaction(b.dataset.id))}
function addOccasion(){openModal(`${modalHead('ثبت مناسبت')}<div class="field"><label>عنوان *</label><input id="oTitle"></div><div class="field"><label>نوع</label><select id="oType"><option value="date">تاریخ مشخص</option><option value="fixed">تکرار هر سال شمسی</option></select></div><div id="oDateBox" class="field"><label>تاریخ شمسی</label><input id="oDate" value="${todayJ()}"></div><div id="oFixedBox" class="two-cols hidden"><div class="field"><label>ماه</label><input id="oMonth" type="number" min="1" max="12"></div><div class="field"><label>روز</label><input id="oDay" type="number" min="1" max="31"></div></div><button type="button" id="saveOccasion" class="primary full">ثبت مناسبت</button>`);$('#oType').onchange=()=>{$('#oDateBox').classList.toggle('hidden',$('#oType').value==='fixed');$('#oFixedBox').classList.toggle('hidden',$('#oType').value!=='fixed')};$('#saveOccasion').onclick=()=>{const title=$('#oTitle').value.trim();if(!title)return toast('عنوان را وارد کنید');if($('#oType').value==='date'){const date=$('#oDate').value.trim();if(!validJ(date))return toast('تاریخ صحیح نیست');db.occasions.push({id:uid(),title,date,fixed:false})}else{const month=Number($('#oMonth').value),day=Number($('#oDay').value);if(month<1||month>12||day<1||day>31)return toast('ماه و روز صحیح نیست');db.occasions.push({id:uid(),title,month,day,fixed:true})}save(`ثبت مناسبت: ${title}`);$('#modal').close();toast('مناسبت ثبت شد')}}
function editOccasion(id){const o=db.occasions.find(x=>x.id===id);if(!o)return;openModal(`${modalHead('ویرایش مناسبت')}<div class="field"><label>عنوان</label><input id="oeTitle" value="${esc(o.title)}"></div>${o.fixed?`<div class="two-cols"><div class="field"><label>ماه</label><input id="oeMonth" type="number" min="1" max="12" value="${o.month}"></div><div class="field"><label>روز</label><input id="oeDay" type="number" min="1" max="31" value="${o.day}"></div></div>`:`<div class="field"><label>تاریخ شمسی</label><input id="oeDate" value="${esc(o.date||todayJ())}"></div>`}<button type="button" id="saveOccEdit" class="primary full">ذخیره تغییرات</button>`);$('#saveOccEdit').onclick=()=>{const title=$('#oeTitle').value.trim();if(!title)return toast('عنوان را وارد کنید');o.title=title;if(o.fixed){const m=Number($('#oeMonth').value),d=Number($('#oeDay').value);if(m<1||m>12||d<1||d>31)return toast('ماه یا روز صحیح نیست');o.month=m;o.day=d}else{const date=$('#oeDate').value.trim();if(!validJ(date))return toast('تاریخ صحیح نیست');o.date=date}save(`ویرایش مناسبت: ${title}`);$('#modal').close();toast('مناسبت ویرایش شد')}}
function globalSearch(){openModal(`${modalHead('جستجوی سریع')}<input id="globalQ" class="search" autofocus placeholder="نام بانی، عامل، تاریخ یا محل..."><div id="globalResults" class="list"></div>`);const run=()=>{const q=$('#globalQ').value.trim();if(!q){$('#globalResults').innerHTML='<p class="muted">عبارت جستجو را وارد کنید.</p>';return}const sr=db.sponsors.filter(s=>[s.name,s.phone].join(' ').includes(q)).map(s=>`<button class="list-item gs" data-kind="s" data-id="${s.id}"><div><h3>بانی: ${esc(s.name)}</h3><p>${esc(s.phone||'')}</p></div></button>`),wr=db.workers.filter(w=>[w.name,w.role,w.phone].join(' ').includes(q)).map(w=>`<button class="list-item gs" data-kind="w" data-id="${w.id}"><div><h3>عامل: ${esc(w.name)}</h3><p>${esc(w.role)}</p></div></button>`),rr=db.rozehs.filter(r=>{const s=sponsorBy(r.sponsorId);return [s?.name,r.place,r.type,(r.dates||[]).join(' ')].join(' ').includes(q)}).map(r=>`<button class="list-item gs" data-kind="r" data-id="${r.id}"><div><h3>روضه: ${esc(sponsorBy(r.sponsorId)?.name||'')}</h3><p>${esc(r.dates.join('، '))} • ${esc(r.place||'')}</p></div></button>`);$('#globalResults').innerHTML=[...sr,...wr,...rr].join('')||'<p class="muted">نتیجه‌ای پیدا نشد.</p>';$$('.gs').forEach(b=>b.onclick=()=>({s:openSponsor,w:openWorker,r:openRozeh}[b.dataset.kind](b.dataset.id)))};$('#globalQ').oninput=run;run()}

function csvCell(v=''){return `"${String(v??'').replace(/"/g,'""')}"`} function downloadText(name,text,type='text/csv;charset=utf-8'){const blob=new Blob(['\ufeff'+text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportRozehCsv(){const rows=[['بانی','تاریخ‌ها','ساعت','نوع','محل','جمع هزینه','مبلغ بانی','مانده بانی']];db.rozehs.forEach(r=>rows.push([sponsorBy(r.sponsorId)?.name||'',r.dates.join(' | '),r.time||'',r.type||'',r.place||'',expenseTotal(r),sponsorCharge(r),sponsorDebt(r.sponsorId)]));downloadText(`rozeh-${todayJ().replaceAll('/','-')}.csv`,rows.map(r=>r.map(csvCell).join(',')).join('\n'))}
function exportLedgerCsv(){const rows=[['نوع','نام','بدهی/طلب','پرداخت/دریافت','مانده']];db.sponsors.forEach(s=>rows.push(['بانی',s.name,db.rozehs.filter(r=>r.sponsorId===s.id).reduce((a,r)=>a+sponsorCharge(r),0),sponsorPaid(s.id),sponsorDebt(s.id)]));db.workers.forEach(w=>rows.push(['عامل',w.name,workerDue(w.id),workerPaid(w.id),workerBalance(w.id)]));downloadText(`accounts-${todayJ().replaceAll('/','-')}.csv`,rows.map(r=>r.map(csvCell).join(',')).join('\n'))}
function exportWorkersCsv(){const rows=[['نام','نقش','تماس','تعداد حضور','حق‌الزحمه','پرداختی','مانده']];db.workers.forEach(w=>{let c=0;db.rozehs.forEach(r=>(r.expenses||[]).forEach(e=>{if(e.workerId===w.id&&e.attended!==false)c++}));rows.push([w.name,w.role,w.phone||'',c,workerDue(w.id),workerPaid(w.id),workerBalance(w.id)])});downloadText(`workers-${todayJ().replaceAll('/','-')}.csv`,rows.map(r=>r.map(csvCell).join(',')).join('\n'))}
function printSummary(){const recv=db.transactions.filter(t=>t.kind==='receive').reduce((s,t)=>s+Number(t.amount||0),0),paid=db.transactions.filter(t=>t.kind==='pay').reduce((s,t)=>s+Number(t.amount||0),0),w=window.open('','_blank');w.document.write(`<html dir="rtl"><head><meta charset="utf-8"><title>گزارش</title><style>body{font-family:Tahoma;padding:30px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccc;padding:8px;text-align:right}h1{color:#0c6b50}</style></head><body><h1>${esc(db.settings.org)}</h1><p>تاریخ گزارش: ${todayJ()}</p><table><tr><th>شاخص</th><th>مقدار</th></tr><tr><td>تعداد بانی</td><td>${db.sponsors.length}</td></tr><tr><td>تعداد مراسم</td><td>${db.rozehs.length}</td></tr><tr><td>کل دریافتی</td><td>${money(recv)}</td></tr><tr><td>کل پرداختی</td><td>${money(paid)}</td></tr><tr><td>مطالبات بانی</td><td>${money(db.sponsors.reduce((s,x)=>s+Math.max(0,sponsorDebt(x.id)),0))}</td></tr><tr><td>بدهی عوامل</td><td>${money(db.workers.reduce((s,x)=>s+Math.max(0,workerBalance(x.id)),0))}</td></tr></table><script>window.print()<\/script></body></html>`);w.document.close()}
function exportBackup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rozeh-backup-v3-${todayJ().replaceAll('/','-')}.json`;a.click();URL.revokeObjectURL(a.href)}
function switchView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:0,behavior:'smooth'})}
function checkReminder(){const n=Number(db.settings.reminder||0);if(!n)return;const upcoming=db.rozehs.flatMap(r=>(r.dates||[]).map(date=>({r,date}))).filter(x=>{const d=dayDiff(x.date,todayJ());return d>=0&&d<=n}).sort((a,b)=>compareJ(a.date,b.date));if(upcoming.length)setTimeout(()=>toast(`${upcoming.length} مراسم در ${n} روز آینده دارید`),700)}
function applyLock(){if(db.settings.pin){$('#lockScreen').classList.remove('hidden');$('#app').classList.add('hidden')}else{$('#lockScreen').classList.add('hidden');$('#app').classList.remove('hidden')}}

$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#prevMonth').onclick=()=>{calMonth--;if(calMonth<1){calMonth=12;calYear--}renderCalendar();renderDashboard()};$('#nextMonth').onclick=()=>{calMonth++;if(calMonth>12){calMonth=1;calYear++}renderCalendar();renderDashboard()};
$('#sponsorSearch').oninput=e=>renderSponsors(e.target.value);$('#rozehSearch').oninput=e=>renderRozehs(e.target.value);$('#workerSearch').oninput=e=>renderWorkers(e.target.value);$$('[data-action="add-sponsor"]').forEach(b=>b.onclick=addSponsor);$$('[data-action="add-worker"]').forEach(b=>b.onclick=addWorker);$$('[data-action="add-rozeh"]').forEach(b=>b.onclick=()=>addRozeh());$$('[data-action="add-transaction"]').forEach(b=>b.onclick=()=>addTransaction());$$('[data-action="add-occasion"]').forEach(b=>b.onclick=addOccasion);$$('[data-action="go-rozehs"]').forEach(b=>b.onclick=()=>switchView('rozehs'));$$('.seg').forEach(b=>b.onclick=()=>{accountTab=b.dataset.accountTab;renderAccounting()});
$('#quickAdd').onclick=()=>{openModal(`${modalHead('ثبت سریع')}<div class="list"><button type="button" class="list-item q" data-q="sponsor"><b>ثبت بانی</b><span>›</span></button><button type="button" class="list-item q" data-q="rozeh"><b>ثبت روضه</b><span>›</span></button><button type="button" class="list-item q" data-q="worker"><b>ثبت عامل</b><span>›</span></button><button type="button" class="list-item q" data-q="trans"><b>ثبت سند مالی</b><span>›</span></button></div>`);$$('.q').forEach(b=>b.onclick=()=>({sponsor:addSponsor,rozeh:()=>addRozeh(),worker:addWorker,trans:()=>addTransaction()}[b.dataset.q])())};$('#globalSearchBtn').onclick=globalSearch;
$('#saveSettings').onclick=()=>{const card=invoicePhone($('#settingBankCard').value),rawSheba=invoicePhone($('#settingBankSheba').value).toUpperCase(),sheba=rawSheba&&!rawSheba.startsWith('IR')?'IR'+rawSheba:rawSheba;if(card&&!/^\d{16}$/.test(card))return toast('شماره کارت باید ۱۶ رقم باشد');if(sheba&&!/^IR\d{24}$/.test(sheba))return toast('شبا باید IR و ۲۴ رقم باشد');db.settings.bankCard=card;db.settings.bankSheba=sheba;db.settings.org=$('#settingOrg').value.trim()||'مدیریت روضه';db.settings.currency=$('#settingCurrency').value;db.settings.pin=$('#settingPin').value.trim();db.settings.reminder=$('#settingReminder').value;save('ویرایش تنظیمات برنامه');toast('تنظیمات ذخیره شد')};$('#unlockBtn').onclick=()=>{if($('#pinInput').value===db.settings.pin){$('#lockScreen').classList.add('hidden');$('#app').classList.remove('hidden');$('#pinError').textContent=''}else $('#pinError').textContent='رمز صحیح نیست'};$('#pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#unlockBtn').click()});
$('#allExpenseDetails').onclick=openAllExpenseDetails;$('#exportData').onclick=exportBackup;$('#exportRozehCsv').onclick=exportRozehCsv;$('#exportLedgerCsv').onclick=exportLedgerCsv;$('#exportWorkersCsv').onclick=exportWorkersCsv;$('#printReport').onclick=printSummary;$('#importData').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.sponsors)||!Array.isArray(data.rozehs))throw 0;if(confirm('اطلاعات فعلی با این نسخه پشتیبان جایگزین شود؟')){db={...emptyDB(),...data,settings:{...emptyDB().settings,...(data.settings||{})},audit:data.audit||[]};save('بازیابی فایل پشتیبان');toast('پشتیبان بازیابی شد')}}catch{toast('فایل پشتیبان معتبر نیست')}};$('#clearAudit').onclick=()=>{if(confirm('تاریخچه عملیات پاک شود؟')){db.audit=[];save();toast('تاریخچه پاک شد')}};

renderAll();applyLock();recover();checkReminder();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
