const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const fmt=n=>(Number(n)||0).toLocaleString('fa-IR');
const money=n=>`${fmt(n)} تومان`;
const KEY='qanat-manager-v1';
const empty=()=>({owners:[],rates:[],payments:[],settings:{name:'مدیریت قنات',currency:'تومان',shareMethod:'oldest'},meta:{version:1,updatedAt:new Date().toISOString()},audit:[]});
let db=(()=>{try{return {...empty(),...(JSON.parse(localStorage.getItem(KEY)||'null')||{})}}catch{return empty()}})();
function save(action=''){if(action)db.audit.unshift({id:uid(),text:action,at:new Date().toISOString()});db.audit=db.audit.slice(0,200);db.meta.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(db));render();}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function j(y,m,d){return `${y}/${String(m).padStart(2,'0')}/${String(d).padStart(2,'0')}`}
function today(){const d=new Date();return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d).replaceAll('۰','0').replaceAll('۱','1').replaceAll('۲','2').replaceAll('۳','3').replaceAll('۴','4').replaceAll('۵','5').replaceAll('۶','6').replaceAll('۷','7').replaceAll('۸','8').replaceAll('۹','9').replaceAll('٫','/').replaceAll('-','/').replace(/\s/g,'')}
function parseDate(s){let x=String(s).replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replaceAll('-','/').split('/').map(Number);return{x:x[0],m:x[1],d:x[2]}}
function yearOf(s){return parseDate(s).x}
function rateFor(y){return db.rates.find(r=>Number(r.year)===Number(y))}
function ownerBy(id){return db.owners.find(o=>o.id===id)}
function ownerDebtByYear(o,y){const r=rateFor(y);return r?Number(o.hours||0)*Number(r.amount||0):0}
function yearlyDebt(o,y){return ownerDebtByYear(o,y)}
function paymentsFor(o){return db.payments.filter(p=>p.ownerId===o.id)}
function totalPayments(o){return paymentsFor(o).reduce((s,p)=>s+Number(p.amount||0),0)}
function allYears(o){const years=new Set(db.rates.map(r=>Number(r.year)));paymentsFor(o).forEach(p=>years.add(yearOf(p.date)));return [...years].sort((a,b)=>a-b)}
function currentJalaliYear(){const m=today().split('/').map(Number);return m[0]||1405}
function statementYears(o,asOfYear=currentJalaliYear()){return allYears(o).filter(y=>y<=Number(asOfYear)&&rateFor(y))}
function lateDifference(o,y,asOfYear){const base=rateFor(y),cur=rateFor(asOfYear);if(!base||!cur||Number(y)>=Number(asOfYear))return 0;return Math.max(0,(Number(cur.amount)||0)-(Number(base.amount)||0))*Number(o.hours||0)}
function statementRows(o,asOfYear=currentJalaliYear()){
 const ys=statementYears(o,asOfYear);
 return ys.map(y=>({year:y,rate:Number(rateFor(y)?.amount||0),debt:yearlyDebt(o,y),delay:lateDifference(o,y,asOfYear)}));
}
function statementTotals(o,asOfYear=currentJalaliYear()){
 const rows=statementRows(o,asOfYear);const debt=rows.reduce((s,r)=>s+r.debt,0);const delay=rows.reduce((s,r)=>s+r.delay,0);const paid=paymentsFor(o).filter(p=>yearOf(p.date)<=Number(asOfYear)).reduce((s,p)=>s+Number(p.amount||0),0);return {debt,delay,paid,total:debt+delay,balance:debt+delay-paid,asOfYear:Number(asOfYear)};
}
function totalDebt(o){return statementTotals(o).total}
function balance(o){return statementTotals(o).balance}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').showModal();$$('.close').forEach(b=>b.onclick=()=>$('#modal').close())}
function card(label,val,cls=''){return `<div class="stat ${cls}"><span>${label}</span><b>${val}</b></div>`}
function render(){
 $('#orgTitle').textContent=db.settings.name;$('#orgSub').textContent='سامانه جامع مدیریت قنات';
 const debt=db.owners.reduce((s,o)=>s+Math.max(0,balance(o)),0), credit=db.owners.reduce((s,o)=>s+Math.max(0,-balance(o)),0), paid=db.payments.reduce((s,p)=>s+Number(p.amount||0),0), hours=db.owners.reduce((s,o)=>s+Number(o.hours||0),0);
 $('#dash').innerHTML=card('مالکین',fmt(db.owners.length))+card('کل ساعات مالکیت',fmt(hours))+card('مطالبات',money(debt),'red')+card('دریافتی',money(paid),'green');
 renderOwners();renderRates();renderRecent();
}
function renderOwners(filter=''){const list=db.owners.filter(o=>(o.name+' '+(o.phone||'')+' '+(o.nationalId||'')).includes(filter));$('#ownerList').innerHTML=list.map(o=>`<div class="list-item owner-card"><button class="owner-open main owner-main-btn" data-id="${o.id}"><h3>${esc(o.name)}</h3><p>${fmt(o.hours)} ساعت ${o.phone?'• '+esc(o.phone):''}</p></button><div class="amount ${balance(o)>0?'danger':''}">${money(balance(o))}<small>${balance(o)>0?'بدهکار':'تسویه/بستانکار'}</small></div><div class="row-actions"><button class="icon-action edit" data-edit-owner="${o.id}" title="ویرایش">✎</button><button class="icon-action delete" data-delete-owner="${o.id}" title="حذف">×</button></div></div>`).join('')||'<p class="muted">هنوز مالکی ثبت نشده است.</p>';$$('.owner-open').forEach(b=>b.onclick=()=>ownerDetail(b.dataset.id));$$('[data-edit-owner]').forEach(b=>b.onclick=e=>{e.stopPropagation();ownerForm(b.dataset.editOwner)});$$('[data-delete-owner]').forEach(b=>b.onclick=e=>{e.stopPropagation();deleteOwner(b.dataset.deleteOwner)})}
function renderRates(){$('#rateList').innerHTML=[...db.rates].sort((a,b)=>b.year-a.year).map(r=>`<div class="list-item"><div class="main"><h3>سال ${fmt(r.year)}</h3><p>نرخ نفقه هر ساعت${r.note?' • '+esc(r.note):''}</p></div><div class="amount">${money(r.amount)}</div><div class="row-actions"><button class="icon-action edit" data-edit-rate="${r.id}" title="ویرایش">✎</button><button class="icon-action delete" data-delete-rate="${r.id}" title="حذف">×</button></div></div>`).join('')||'<p class="muted">نرخ سالانه ثبت نشده است.</p>';$$('[data-edit-rate]').forEach(b=>b.onclick=()=>rateForm(b.dataset.editRate));$$('[data-delete-rate]').forEach(b=>b.onclick=()=>deleteRate(b.dataset.deleteRate))}
function renderRecent(){$('#recent').innerHTML=[...db.payments].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,6).map(p=>{const o=ownerBy(p.ownerId);return `<div class="list-item"><div class="main"><h3>${esc(o?.name||'مالک حذف‌شده')}</h3><p>${esc(p.date)} • ${esc(p.description||'واریزی')}</p></div><div class="amount green-text">+ ${money(p.amount)}</div><div class="row-actions"><button class="icon-action edit" onclick="${o?`paymentForm('${o.id}','${p.id}')`:'toast(\'مالک این سند حذف شده است\')'}" title="ویرایش">✎</button><button class="icon-action delete" onclick="deletePayment('${p.id}')" title="حذف">×</button></div></div>`}).join('')||'<p class="muted">هنوز واریزی ثبت نشده است.</p>'}
function ownerDetail(id){const o=ownerBy(id);if(!o)return;const st=statementTotals(o);const rows=statementRows(o).map(r=>`<tr><td>${fmt(r.year)}</td><td>${fmt(o.hours)}</td><td>${money(r.rate)}</td><td>${money(r.debt)}</td><td>${r.delay?money(r.delay):'—'}</td><td>${money(r.debt+r.delay)}</td></tr>`).join('');const payments=paymentsFor(o).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(p=>`<div class="ledger-row"><span>${esc(p.date)}<small>${esc(p.description||'واریزی')}${p.tracking?' • پیگیری '+esc(p.tracking):''}${p.bank?' • '+esc(p.bank):''}</small></span><b class="green-text">+ ${money(p.amount)}</b><span class="row-actions ledger-actions"><button class="icon-action edit" onclick="paymentForm('${id}','${p.id}')" title="ویرایش">✎</button><button class="icon-action delete" onclick="deletePayment('${p.id}')" title="حذف">×</button></span></div>`).join('');openModal(`<div class="modal-head"><h2>${esc(o.name)}</h2><button class="close">×</button></div><div class="profile"><div><b>${fmt(o.hours)}</b><small>ساعت مالکیت</small></div><div><b>${money(st.total)}</b><small>جمع بدهی تا ${fmt(st.asOfYear)}</small></div><div><b>${money(st.delay)}</b><small>مابه‌التفاوت تأخیر</small></div><div><b>${money(st.balance)}</b><small>مانده قابل پرداخت</small></div></div><div class="detail-grid"><div><b>کد ملی:</b> ${esc(o.nationalId||'-')}</div><div><b>تلفن:</b> ${esc(o.phone||'-')}</div><div class="wide"><b>آدرس:</b> ${esc(o.address||'-')}</div></div><div class="notice"><b>قاعده تأخیر:</b> برای هر سال پرداخت‌نشده، مابه‌التفاوت نرخ همان سال تا نرخ سال صدور صورت‌حساب محاسبه می‌شود. برای سال جاری مابه‌التفاوت تأخیر صفر است.</div><h3>صورت‌حساب سنواتی</h3><div class="table-wrap"><table><thead><tr><th>سال</th><th>ساعت</th><th>نرخ</th><th>بدهی</th><th>مابه‌التفاوت تأخیر</th><th>جمع</th></tr></thead><tbody>${rows||'<tr><td colspan="6">نرخی برای سال‌های این مالک ثبت نشده</td></tr>'}</tbody></table></div><div class="statement-total"><div><span>جمع بدهی نفقه</span><b>${money(st.debt)}</b></div><div><span>مابه‌التفاوت تأخیر</span><b>${money(st.delay)}</b></div><div><span>جمع کل بدهی</span><b>${money(st.total)}</b></div><div><span>پرداختی ثبت‌شده</span><b>${money(st.paid)}</b></div><div class="grand"><span>مانده قابل پرداخت</span><b>${money(st.balance)}</b></div></div><h3>گردش واریزی</h3><div class="ledger">${payments||'<p class="muted">بدون واریزی</p>'}</div><div class="modal-actions"><button class="secondary" onclick="ownerForm('${id}')">ویرایش مالک</button><button class="primary" onclick="paymentForm('${id}')">ثبت واریزی</button><button class="secondary" onclick="shareStatement('${id}')">ارسال صورت‌حساب</button><button class="secondary" onclick="printStatement('${id}')">چاپ / PDF</button><button class="danger-btn" onclick="deleteOwner('${id}')">حذف مالک</button></div>`) }

function ownerForm(id=null){const o=id?ownerBy(id):{};openModal(`<div class="modal-head"><h2>${id?'ویرایش مالک':'ثبت مالک جدید'}</h2><button class="close">×</button></div><div class="form-grid"><label>نام و نام خانوادگی<input id="fName" value="${esc(o.name||'')}"/></label><label>ساعت مالکیت<input id="fHours" inputmode="decimal" type="number" value="${o.hours||''}"/></label><label>کد ملی<input id="fNid" inputmode="numeric" value="${esc(o.nationalId||'')}"/></label><label>شماره تماس<input id="fPhone" inputmode="tel" value="${esc(o.phone||'')}"/></label><label class="wide">آدرس<textarea id="fAddress">${esc(o.address||'')}</textarea></label><label class="wide">توضیحات<textarea id="fNote">${esc(o.note||'')}</textarea></label></div><button class="primary full" onclick="saveOwner('${id||''}')">ذخیره مالک</button>`)}
function saveOwner(id){const name=$('#fName').value.trim(),hours=Number($('#fHours').value);if(!name||hours<=0)return toast('نام و ساعت مالکیت را وارد کنید');const o=id?ownerBy(id):{id:uid()};Object.assign(o,{name,hours,nationalId:$('#fNid').value.trim(),phone:$('#fPhone').value.trim(),address:$('#fAddress').value.trim(),note:$('#fNote').value.trim()});if(!id)db.owners.push(o);$('#modal').close();save(`${id?'ویرایش':'ثبت'} مالک ${name}`);toast('اطلاعات مالک ذخیره شد')}
function rateForm(id=null){const r=id?db.rates.find(x=>x.id===id):{};openModal(`<div class="modal-head"><h2>${id?'ویرایش نرخ نفقه':'ثبت نرخ نفقه سالانه'}</h2><button class="close">×</button></div><div class="form-grid"><label>سال شمسی<input id="rYear" inputmode="numeric" value="${id?fmt(r.year):''}" placeholder="۱۴۰۵"/></label><label>مبلغ هر ساعت (تومان)<input id="rAmount" inputmode="numeric" value="${id?fmt(r.amount):''}" placeholder="۱,۰۰۰,۰۰۰"/></label><label class="wide">توضیح<textarea id="rNote">${esc(r.note||'')}</textarea></label></div><button class="primary full" onclick="saveRate('${id||''}')">${id?'ذخیره تغییرات':'ثبت نرخ'}</button>`)}
function saveRate(id=''){const y=Number($('#rYear').value.replace(/\D/g,'')),amount=Number($('#rAmount').value.replace(/\D/g,''));if(!y||!amount)return toast('سال و مبلغ را وارد کنید');const duplicate=db.rates.find(r=>Number(r.year)===y&&r.id!==id);if(duplicate)return toast('برای این سال قبلاً نرخ ثبت شده است');if(id){const r=db.rates.find(x=>x.id===id);if(!r)return;Object.assign(r,{year:y,amount,note:$('#rNote').value.trim()})}else db.rates.push({id:uid(),year:y,amount,note:$('#rNote').value.trim()});$('#modal').close();save(`${id?'ویرایش':'ثبت'} نرخ نفقه سال ${y}`);toast('نرخ سالانه ذخیره شد')}
function paymentForm(ownerId,paymentId=null){const o=ownerBy(ownerId),p=paymentId?db.payments.find(x=>x.id===paymentId):{};if(!o)return;openModal(`<div class="modal-head"><h2>${paymentId?'ویرایش سند واریزی':'ثبت واریزی'} — ${esc(o.name)}</h2><button class="close">×</button></div><div class="form-grid"><label>تاریخ واریز<input id="pDate" value="${esc(p.date||today())}"/></label><label>مبلغ (تومان)<input id="pAmount" inputmode="numeric" value="${p.amount?fmt(p.amount):''}"/></label><label>شماره پیگیری<input id="pTrack" inputmode="numeric" value="${esc(p.tracking||'')}"/></label><label>حساب/بانک<input id="pBank" value="${esc(p.bank||'')}"/></label><label class="wide">شرح<textarea id="pDesc">${esc(p.description||'واریز بابت نفقه')}</textarea></label></div><button class="primary full" onclick="savePayment('${ownerId}','${paymentId||''}')">${paymentId?'ذخیره تغییرات':'ثبت سند واریزی'}</button>`)}
function savePayment(ownerId,id=''){const amount=Number($('#pAmount').value.replace(/\D/g,''));if(!amount)return toast('مبلغ را وارد کنید');const data={ownerId,date:$('#pDate').value.trim()||today(),amount,tracking:$('#pTrack').value.trim(),bank:$('#pBank').value.trim(),description:$('#pDesc').value.trim()};if(id){const p=db.payments.find(x=>x.id===id);if(!p)return;Object.assign(p,data)}else db.payments.push({id:uid(),...data,createdAt:new Date().toISOString()});$('#modal').close();save(`${id?'ویرایش':'ثبت'} واریزی ${money(amount)} برای ${ownerBy(ownerId).name}`);toast(id?'سند واریزی ویرایش شد':'سند واریزی ثبت شد')}
function deleteOwner(id){const o=ownerBy(id);if(!confirm(`مالک «${o.name}» حذف شود؟`))return;db.owners=db.owners.filter(x=>x.id!==id);db.payments=db.payments.filter(x=>x.ownerId!==id);$('#modal').close();save(`حذف مالک ${o.name}`);toast('مالک حذف شد')}
function deleteRate(id){const r=db.rates.find(x=>x.id===id);if(!r)return;const used=db.owners.some(o=>statementRows(o).some(x=>x.year===Number(r.year)));if(!confirm(`نرخ سال ${fmt(r.year)} حذف شود؟\n${used?'این نرخ در محاسبات مالکین استفاده شده است و با حذف آن بدهی همان سال از صورت‌حساب‌ها حذف می‌شود.\n\n':''}این عملیات قابل بازگشت نیست.`))return;db.rates=db.rates.filter(x=>x.id!==id);save(`حذف نرخ نفقه سال ${r.year}`);toast('نرخ حذف شد')}
function deletePayment(id){const p=db.payments.find(x=>x.id===id);if(!p)return;const o=ownerBy(p.ownerId);if(!confirm(`سند واریزی ${money(p.amount)} در تاریخ ${p.date} حذف شود؟`))return;db.payments=db.payments.filter(x=>x.id!==id);$('#modal').close();save(`حذف واریزی ${money(p.amount)} برای ${o?.name||'مالک'}`);toast('سند واریزی حذف شد');if(o)ownerDetail(o.id)}
function statementText(id){const o=ownerBy(id),st=statementTotals(o),rows=statementRows(o);let s=`صورت‌حساب مالک قنات
${db.settings.name}

مالک: ${o.name}
ساعت مالکیت: ${fmt(o.hours)} ساعت
سال صدور: ${fmt(st.asOfYear)}

`;rows.forEach(r=>{s+=`سال ${fmt(r.year)} | نرخ: ${money(r.rate)} | بدهی: ${money(r.debt)} | مابه‌التفاوت تأخیر: ${money(r.delay)} | جمع: ${money(r.debt+r.delay)}\n`});s+=`
جمع بدهی نفقه: ${money(st.debt)}
مابه‌التفاوت تأخیر: ${money(st.delay)}
جمع کل بدهی: ${money(st.total)}
پرداختی ثبت‌شده: ${money(st.paid)}
مانده قابل پرداخت: ${money(st.balance)}`;return s}
async function shareStatement(id){const o=ownerBy(id),text=statementText(id);if(navigator.share){try{await navigator.share({title:`صورت‌حساب ${o.name}`,text});toast('صفحه ارسال باز شد');return}catch(e){if(e?.name==='AbortError')return}}try{await navigator.clipboard?.writeText(text);toast('متن صورت‌حساب کپی شد')}catch{toast('متن صورت‌حساب آماده ارسال است')}}
function printStatement(id){const o=ownerBy(id);if(!o)return;const st=statementTotals(o),rows=statementRows(o).map(r=>`<tr><td>${fmt(r.year)}</td><td>${fmt(o.hours)}</td><td>${money(r.rate)}</td><td>${money(r.debt)}</td><td>${money(r.delay)}</td><td>${money(r.debt+r.delay)}</td></tr>`).join('');$('#printSheet')?.remove();const sheet=document.createElement('section');sheet.id='printSheet';sheet.innerHTML=`<div class="print-card"><div class="print-brand">${esc(db.settings.name)}</div><h1>صورت‌حساب مالک قنات</h1><div class="print-meta"><span>مالک: <b>${esc(o.name)}</b></span><span>ساعت مالکیت: <b>${fmt(o.hours)}</b></span><span>سال صدور: <b>${fmt(st.asOfYear)}</b></span></div><table><thead><tr><th>سال</th><th>ساعت</th><th>نرخ هر ساعت</th><th>بدهی نفقه</th><th>مابه‌التفاوت تأخیر</th><th>جمع</th></tr></thead><tbody>${rows}</tbody></table><div class="print-totals"><div>جمع بدهی نفقه: <b>${money(st.debt)}</b></div><div>مابه‌التفاوت تأخیر: <b>${money(st.delay)}</b></div><div>جمع کل بدهی: <b>${money(st.total)}</b></div><div>پرداختی ثبت‌شده: <b>${money(st.paid)}</b></div><div class="print-grand">مانده قابل پرداخت: <b>${money(st.balance)}</b></div></div><p class="print-rule">مابه‌التفاوت تأخیر هر سال برابر است با نرخ سال صدور صورت‌حساب منهای نرخ همان سال، ضربدر ساعات مالکیت.</p></div>`;document.body.appendChild(sheet);requestAnimationFrame(()=>window.print());setTimeout(()=>sheet.remove(),1000)}

async function exportData(){const text=JSON.stringify(db,null,2);if(navigator.share){try{await navigator.share({title:'پشتیبان مدیریت قنات',text});toast('پشتیبان برای ارسال آماده شد');return}catch(e){if(e?.name==='AbortError')return}}try{await navigator.clipboard?.writeText(text);toast('پشتیبان کپی شد')}catch{toast('امکان اشتراک‌گذاری پشتیبان در این محیط وجود ندارد')}}
async function exportCSV(){const rows=[['مالک','ساعت','سال','نرخ هر ساعت','بدهی نفقه','مابه‌التفاوت تأخیر','جمع بدهی']];db.owners.forEach(o=>statementRows(o).forEach(r=>rows.push([o.name,o.hours,r.year,r.rate,r.debt,r.delay,r.debt+r.delay])));const csv='\uFEFF'+rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');if(navigator.share){try{await navigator.share({title:'گزارش مالی قنات',text:csv});toast('گزارش برای ارسال آماده شد');return}catch(e){if(e?.name==='AbortError')return}}try{await navigator.clipboard?.writeText(csv);toast('گزارش CSV کپی شد')}catch{toast('گزارش آماده کپی است')}}
$('#ownerSearch').oninput=e=>renderOwners(e.target.value.trim());
$$('[data-action="owner"]').forEach(b=>b.onclick=()=>ownerForm());$('#addRate').onclick=rateForm;$('#exportData').onclick=exportData;$('#exportCSV').onclick=exportCSV;
$('#settingsBtn').onclick=()=>openModal(`<div class="modal-head"><h2>تنظیمات</h2><button class="close">×</button></div><label>نام قنات / مجموعه<input id="sName" value="${esc(db.settings.name)}"/></label><button class="primary full" onclick="db.settings.name=$('#sName').value.trim()||'مدیریت قنات';$('#modal').close();save('ویرایش تنظیمات')">ذخیره</button>`);
function switchView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v))}
$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});

// --- Water circulation calendar ---
if(!db.settings.water) db.settings.water={startDate:today(),startTime:'06:00'};
let waterCursor=new Date();
function faDigitsToEn(s){return String(s).replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c));}
function jalaliToGregorian(jy,jm,jd){jy=+jy;jm=+jm;jd=+jd;let gy=jy<=979?621:1600;let y=jy-(jy<=979?0:979);let days=365*y+Math.floor(y/33)*8+Math.floor((y%33+3)/4)+78+jd+(jm<7?(jm-1)*31:(jm-7)*30+186);gy+=400*Math.floor(days/146097);days%=146097;if(days>36524){gy+=100*Math.floor(--days/36524);days%=36524;if(days>=365)days++;}gy+=4*Math.floor(days/1461);days%=1461;if(days>365){gy+=Math.floor((days-1)/365);days=(days-1)%365;}let gd=days+1;const leap=(gy%4===0&&gy%100!==0)||gy%400===0;const gmd=[31,leap?29:28,31,30,31,30,31,31,30,31,30,31];let gm=1;while(gd>gmd[gm-1]){gd-=gmd[gm-1];gm++;}return new Date(gy,gm-1,gd);}
function gregToJalaliDate(d){return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d).replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/-/g,'/').replace(/\s/g,'');}
function parseJalaliDateTime(s,time='06:00'){const [y,m,d]=faDigitsToEn(String(s).replaceAll('-','/')).split('/').map(Number);if(!y||!m||!d)return null;const g=jalaliToGregorian(y,m,d);const [hh,mm]=(time||'06:00').split(':').map(Number);g.setHours(hh||0,mm||0,0,0);return g;}
function ownerSequence(){return [...db.owners].filter(o=>Number(o.hours)>0).sort((a,b)=>String(a.name).localeCompare(String(b.name),'fa'));}
function waterTotalHours(){return ownerSequence().reduce((s,o)=>s+Number(o.hours||0),0);}
function turnAt(base, owners, cycleHours){if(!owners.length)return null;let hours=((base.getTime()-cycleHours*3600000*0)% (cycleHours*3600000)+cycleHours*3600000)%(cycleHours*3600000);let acc=0;for(const o of owners){const h=Number(o.hours||0);if(hours<acc+h){const offset=hours-acc;const start=new Date(base.getTime()-offset*3600000);const end=new Date(start.getTime()+h*3600000);return {o,start,end};}acc+=h;}return {o:owners[owners.length-1],start:base,end:new Date(base.getTime()+Number(owners.at(-1).hours)*3600000)};}
function generateWaterTurns(monthDate){const owners=ownerSequence(),total=waterTotalHours();if(!owners.length||!total)return[];const start=parseJalaliDateTime(db.settings.water.startDate,db.settings.water.startTime);if(!start)return[];const first=new Date(monthDate.getFullYear(),monthDate.getMonth(),1);const last=new Date(monthDate.getFullYear(),monthDate.getMonth()+1,0,23,59,59);const turns=[];const cycleMs=total*3600000;let base=start;const spanStart=new Date(first.getTime()-cycleMs*2),spanEnd=new Date(last.getTime()+cycleMs*2);let n=Math.floor((spanStart.getTime()-start.getTime())/cycleMs)-2;base=new Date(start.getTime()+n*cycleMs);let guard=0;while(base<spanEnd&&guard++<2000){for(const o of owners){const end=new Date(base.getTime()+Number(o.hours||0)*3600000);if(end>=spanStart&&base<=spanEnd)turns.push({owner:o,start:new Date(base),end});base=end;} }return turns;}
function fmtHM(d){return d.toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'});}
function waterSettings(){const w=db.settings.water||{startDate:today(),startTime:'06:00'};openModal(`<div class="modal-head"><h2>تنظیم مدار آب</h2><button class="close">×</button></div><div class="water-note">مدار بر اساس ساعت مالکیت ساخته می‌شود و از زمان شروع تعیین‌شده به ترتیب مالکین تکرار می‌گردد. مجموع ساعت مالکین، طول یک مدار را مشخص می‌کند.</div><div class="form-grid"><label>تاریخ شروع مدار<input id="wDate" value="${esc(w.startDate||today())}" placeholder="۱۴۰۵/۰۱/۰۱"/></label><label>ساعت شروع<input id="wTime" type="time" value="${esc(w.startTime||'06:00')}"/></label></div><button class="primary full" onclick="saveWaterSettings()">ذخیره و ساخت تقویم</button>`)}
function saveWaterSettings(){const date=$('#wDate').value.trim(),time=$('#wTime').value;if(!parseJalaliDateTime(date,time))return toast('تاریخ شروع مدار صحیح نیست');db.settings.water={startDate:date,startTime:time||'06:00'};$('#modal').close();save('تنظیم مدار آب');toast('تقویم مدار آب به‌روزرسانی شد');renderWater();}
function waterPrev(){waterCursor=new Date(waterCursor.getFullYear(),waterCursor.getMonth()-1,1);renderWater()}
function waterNext(){waterCursor=new Date(waterCursor.getFullYear(),waterCursor.getMonth()+1,1);renderWater()}
function renderWater(){const el=$('#waterCalendar');if(!el)return;const owners=ownerSequence(),total=waterTotalHours();const title=new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'long'}).format(waterCursor);$('#waterMonth').textContent=title;$('#waterSummary').innerHTML=`<div class="water-summary"><div class="mini"><b>${fmt(total)}</b><span>ساعت هر مدار</span></div><div class="mini"><b>${fmt(owners.length)}</b><span>مالک در مدار</span></div><div class="mini"><b>${esc(db.settings.water?.startTime||'06:00')}</b><span>ساعت شروع</span></div></div>`;if(!owners.length){el.innerHTML='<div class="water-empty" style="grid-column:1/-1">ابتدا مالکین و ساعت مالکیت آنها را ثبت کنید تا تقویم مدار آب ساخته شود.</div>';$('#waterSequence').innerHTML='';return;}const turns=generateWaterTurns(waterCursor);const days=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'];let first=new Date(waterCursor.getFullYear(),waterCursor.getMonth(),1);let offset=(first.getDay()+1)%7;let cells='';days.forEach(d=>cells+=`<div class="water-head">${d}</div>`);for(let i=0;i<offset;i++)cells+='<div></div>';const lastDay=new Date(waterCursor.getFullYear(),waterCursor.getMonth()+1,0).getDate();for(let day=1;day<=lastDay;day++){const d=new Date(waterCursor.getFullYear(),waterCursor.getMonth(),day);const jdate=gregToJalaliDate(d);const dayTurns=turns.filter(t=>t.start<new Date(d.getFullYear(),d.getMonth(),day+1)&&t.end>=new Date(d.getFullYear(),d.getMonth(),day));const relevant=dayTurns.slice(0,4);cells+=`<div class="water-day ${gregToJalaliDate(new Date())===jdate?'today-day':''}"><div class="water-day-num">${jdate.split('/').pop()}</div>${relevant.map(t=>`<span class="turn"><b>${esc(t.owner.name)}</b><small>${fmtHM(t.start)} تا ${fmtHM(t.end)}</small></span>`).join('')}</div>`;}el.innerHTML=cells;$('#waterSequence').innerHTML=owners.map((o,i)=>`<div class="seq-item"><div class="seq-main"><span class="seq-no">${fmt(i+1)}</span><div><b>${esc(o.name)}</b><small>ساعت مالکیت در هر مدار</small></div></div><span class="seq-hours">${fmt(o.hours)} ساعت</span></div>`).join('');}
const oldSwitchView=switchView;switchView=function(v){oldSwitchView(v);if(v==='water'){waterCursor=new Date(waterCursor.getFullYear(),waterCursor.getMonth(),1);renderWater();}};
const oldRender=render;render=function(){oldRender();if($('#waterCalendar'))renderWater();};
